// data.h

/*
	<begin copyright stuff>

	Copyright 2001 Joshua Stewart

	This file is part of Scarbble.

    Scarbble is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Scarbble is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Scarbble; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

	<end copyright stuff>
*/

/*	This is generated by an allegro data file editing utility to help
	when referencing data elements from an allegro data file
*/

/* Allegro datafile object indexes, produced by grabber v3.9.37 (CVS), MSVC.s */
/* Datafile: c:\uni sem2 2001\cpp\assignment2\data\data.dat */
/* Date: Sun Oct 21 13:23:55 2001 */
/* Do not hand edit! */

// cant have identifiers starting with numbers.. *tsk tsk* Bad grabber!.. BAD!
//#define 0_BMP                            0        /* BMP  */

#define A_BMP                            1        /* BMP  */
#define B_BMP                            2        /* BMP  */
#define C_BMP                            3        /* BMP  */
#define D_BMP                            4        /* BMP  */
#define E_BMP                            5        /* BMP  */
#define F_BMP                            6        /* BMP  */
#define G_BMP                            7        /* BMP  */
#define H_BMP                            8        /* BMP  */
#define I_BMP                            9        /* BMP  */
#define J_BMP                            10       /* BMP  */
#define K_BMP                            11       /* BMP  */
#define L_BMP                            12       /* BMP  */
#define M_BMP                            13       /* BMP  */
#define N_BMP                            14       /* BMP  */
#define O_BMP                            15       /* BMP  */
#define P_BMP                            16       /* BMP  */
#define Q_BMP                            17       /* BMP  */
#define R_BMP                            18       /* BMP  */
#define S_BMP                            19       /* BMP  */
#define T_BMP                            20       /* BMP  */
#define U_BMP                            21       /* BMP  */
#define V_BMP                            22       /* BMP  */
#define W_BMP                            23       /* BMP  */
#define X_BMP                            24       /* BMP  */
#define Y_BMP                            25       /* BMP  */
#define Z_BMP                            26       /* BMP  */
#define ZANIMATION                       27       /* FLIC */
#define ZDONE_BMP                        28       /* BMP  */
#define ZEXIT_BMP                        29       /* BMP  */
#define ZRESET_BMP                       30       /* BMP  */
#define ZSCORE_BMP                       31       /* BMP  */
#define ZSKIP_BMP                        32       /* BMP  */
#define ZSPAM_BMP                        33       /* BMP  */
#define ZSTAR_BMP                        34       /* BMP  */
#define ZSWAP_BMP                        35       /* BMP  */

